import { z } from "zod";
export const signupSchema = z.object({ name: z.string().trim().min(2).max(80), email: z.string().trim().email().max(320), password: z.string().min(8).max(128), role: z.enum(["BUYER", "SELLER", "NGO"]) });
export const loginSchema = z.object({ email: z.string().trim().email().max(320), password: z.string().min(1).max(128) });
export const buyerProfileSchema = z.object({ name: z.string().trim().min(2).max(80), city: z.string().trim().max(80).optional(), state: z.string().trim().max(80).optional(), pincode: z.string().regex(/^\d{6}$/).optional() });
export const sellerProfileSchema = z.object({ trustScore: z.never().optional() });
export const placeholderSchema = z.object({ acknowledged: z.literal(true) });
export type SignupInput = z.infer<typeof signupSchema>;
export type LoginInput = z.infer<typeof loginSchema>;

export const businessSchema = z.object({
  name: z.string().trim().min(2).max(160), type: z.enum(["RESTAURANT", "HOTEL", "BAKERY", "CAFE", "MESS", "CATERER", "WEDDING_EVENT", "SUPERMARKET", "CLOUD_KITCHEN", "CORPORATE_CAFETERIA", "OTHER"]),
  description: z.string().trim().max(2000).optional(), phone: z.string().trim().max(30).optional(), email: z.string().trim().email().max(320).optional(), address: z.string().trim().max(500).optional(), city: z.string().trim().max(80).optional(), state: z.string().trim().max(80).optional(), pincode: z.string().regex(/^\d{6}$/).optional(), latitude: z.number().min(-90).max(90).optional(), longitude: z.number().min(-180).max(180).optional(), fssaiNumber: z.string().trim().max(80).optional(), pickupAvailable: z.boolean().optional(), deliveryAvailable: z.boolean().optional(), deliveryRadiusKm: z.number().positive().max(100).optional(), deliveryBaseFee: z.number().int().nonnegative().max(100000).optional(), deliveryPerKmFee: z.number().int().nonnegative().max(100000).optional(),
});

export const listingSchema = z.object({
  name: z.string().trim().min(2).max(160), categoryId: z.string().uuid(), listingType: z.enum(["EXACT", "SURPRISE_BOX"]), foodType: z.enum(["VEGETARIAN", "NON_VEGETARIAN", "VEGAN", "JAIN", "OTHER"]), description: z.string().trim().max(2000).optional(), originalPrice: z.number().int().nonnegative(), sellingPrice: z.number().int().nonnegative(), quantity: z.number().int().positive(), unit: z.enum(["PORTION", "PIECE", "BOX", "KG", "GRAM", "LITER", "PACK", "ITEM"]), preparedAt: z.string().datetime().optional(), pickupStart: z.string().datetime(), pickupEnd: z.string().datetime(), packagingInfo: z.string().trim().max(1000).optional(), allergenInfo: z.string().trim().max(1000).optional(),
}).superRefine((value, ctx) => { if (value.sellingPrice > value.originalPrice) ctx.addIssue({ code: "custom", path: ["sellingPrice"], message: "Surplus price cannot exceed original price." }); if (new Date(value.pickupStart) >= new Date(value.pickupEnd)) ctx.addIssue({ code: "custom", path: ["pickupEnd"], message: "Pickup end must be after pickup start." }); if (value.preparedAt && new Date(value.preparedAt) > new Date(value.pickupStart)) ctx.addIssue({ code: "custom", path: ["preparedAt"], message: "Prepared time cannot be after pickup start." }); });

export const inventoryAdjustmentSchema = z.object({ totalQuantity: z.number().int().nonnegative() });

export const marketplaceQuerySchema = z.object({ q: z.string().trim().max(100).optional(), category: z.string().trim().max(80).optional(), foodType: z.enum(["VEGETARIAN", "NON_VEGETARIAN", "VEGAN", "JAIN", "OTHER"]).optional(), minPrice: z.coerce.number().int().nonnegative().optional(), maxPrice: z.coerce.number().int().nonnegative().optional(), sort: z.enum(["recommended", "nearest", "ending-soon", "lowest-price", "highest-discount"]).default("recommended"), page: z.coerce.number().int().min(1).max(10000).default(1), city: z.string().trim().max(80).optional(), lat: z.coerce.number().min(-90).max(90).optional(), lng: z.coerce.number().min(-180).max(180).optional() });
export type MarketplaceQuery = z.infer<typeof marketplaceQuerySchema>;

export const cartItemSchema = z.object({ listingId: z.string().uuid(), quantity: z.number().int().positive().max(99) });
export const cartUpdateSchema = z.object({ quantity: z.number().int().positive().max(99) });
export const checkoutSchema = z.object({ idempotencyKey: z.string().trim().min(16).max(128) });
export const addressSchema = z.object({ label: z.string().trim().min(1).max(40), recipientName: z.string().trim().min(2).max(120), phone: z.string().trim().max(30).optional(), addressLine1: z.string().trim().min(3).max(200), addressLine2: z.string().trim().max(200).optional(), locality: z.string().trim().max(100).optional(), city: z.string().trim().min(2).max(80), state: z.string().trim().min(2).max(80), postalCode: z.string().regex(/^\d{6}$/), latitude: z.number().min(-90).max(90).optional(), longitude: z.number().min(-180).max(180).optional() });
export const fulfillmentSchema = z.object({ method: z.enum(["PICKUP", "DELIVERY"]), addressId: z.string().uuid().optional() }).superRefine((value, ctx) => { if (value.method === "DELIVERY" && !value.addressId) ctx.addIssue({ code: "custom", path: ["addressId"], message: "A delivery address is required." }); });
export const ngoProfileSchema = z.object({ organizationName: z.string().trim().min(2).max(160), contactPerson: z.string().trim().min(2).max(120), phone: z.string().trim().max(30).optional(), description: z.string().trim().max(2000).optional(), serviceArea: z.string().trim().max(160).optional(), address: z.string().trim().max(300).optional(), operatingHours: z.string().trim().max(160).optional() });
export const donationSchema = z.object({ listingId: z.string().uuid(), quantity: z.number().int().positive().max(100000) });
export const donationReservationSchema = z.object({ quantity: z.number().int().positive().max(100000) });
export const operatingHourSchema = z.object({ dayOfWeek: z.number().int().min(0).max(6), openTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), closeTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/) }).superRefine((value, ctx) => { if (value.openTime >= value.closeTime) ctx.addIssue({ code: "custom", path: ["closeTime"], message: "Closing time must be after opening time." }); });
export const operatingHoursSchema = z.object({ hours: z.array(operatingHourSchema).max(21) }).superRefine((value, ctx) => { const keys = value.hours.map((hour) => `${hour.dayOfWeek}:${hour.openTime}:${hour.closeTime}`); if (new Set(keys).size !== keys.length) ctx.addIssue({ code: "custom", path: ["hours"], message: "Duplicate operating hours are not allowed." }); });
export const sellerListingQuerySchema = z.object({ q: z.string().trim().max(100).optional(), status: z.enum(["DRAFT", "PENDING_REVIEW", "ACTIVE", "PAUSED", "SOLD_OUT", "EXPIRED", "BLOCKED", "CANCELLED"]).optional(), categoryId: z.string().uuid().optional(), foodType: z.enum(["VEGETARIAN", "NON_VEGETARIAN", "VEGAN", "JAIN", "OTHER"]).optional(), listingType: z.enum(["EXACT", "SURPRISE_BOX"]).optional(), page: z.coerce.number().int().min(1).max(10000).default(1), pageSize: z.coerce.number().int().min(1).max(100).default(25), sort: z.enum(["createdAt", "pickupEnd", "name"]).default("createdAt"), direction: z.enum(["asc", "desc"]).default("desc") });
export const bulkListingActionSchema = z.object({ listingIds: z.array(z.string().uuid()).min(1).max(100), action: z.enum(["PAUSE", "RESUME", "CANCEL"]) });
export const orderTransitionSchema = z.object({ status: z.enum(["CONFIRMED", "PREPARING", "READY_FOR_PICKUP"]) });
export const cancellationSchema = z.object({ reason: z.string().trim().max(500).optional() });
export const pickupVerificationSchema = z.object({ pickupCode: z.string().regex(/^\d{6}$/) });
export const paymentWebhookSchema = z.object({ provider: z.string().trim().min(2).max(40), eventId: z.string().trim().min(3).max(200), eventType: z.string().trim().min(3).max(120), orderId: z.string().uuid(), providerPaymentId: z.string().trim().max(200).optional(), status: z.enum(["SUCCESS", "FAILED", "REFUNDED"]) });
