"use client";

import { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Clock3, Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";

type Item = { listingId: string; quantity: number; listing: { name: string; sellingPrice: number; unit: string; pickupEnd: string; images: { url: string; altText: string }[] } };

export function CartClient({ initialItems }: { initialItems: Item[] }) {
  const [items, setItems] = useState(initialItems); const [busy, setBusy] = useState(false); const subtotal = items.reduce((sum, item) => sum + item.listing.sellingPrice * item.quantity, 0);
  async function update(listingId: string, quantity: number) { setBusy(true); const response = await fetch("/api/buyer/cart", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ listingId, quantity }) }); if (response.ok) setItems((current) => quantity < 1 ? current.filter((item) => item.listingId !== listingId) : current.map((item) => item.listingId === listingId ? { ...item, quantity } : item)); setBusy(false); }
  if (!items.length) return <div className="empty-state"><ShoppingBag className="mx-auto size-9 text-[var(--accent)]" /><h2 className="mt-5 text-2xl font-black">Your cart is empty</h2><p className="mt-2">Find eligible surplus food before it is gone.</p><Link href="/explore" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[var(--foreground)] px-5 py-3 font-bold text-[var(--background)]">Explore food <ArrowRight className="size-4" /></Link></div>;
  return <div className="grid gap-6 lg:grid-cols-[1fr_360px] lg:items-start"><section className="space-y-3">{items.map((item) => <article key={item.listingId} className="surface-card flex gap-4 p-4 sm:p-5">{item.listing.images[0] ? <Image src={item.listing.images[0].url} alt={item.listing.images[0].altText} width={112} height={112} unoptimized sizes="112px" className="h-24 w-24 shrink-0 rounded-2xl object-cover sm:h-28 sm:w-28" /> : <div className="grid h-24 w-24 shrink-0 place-items-center rounded-2xl bg-[var(--surface-muted)] text-xs font-bold text-[var(--muted)]">Food</div>}<div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><h2 className="truncate text-base font-black">{item.listing.name}</h2><p className="mt-1 text-sm font-semibold text-[var(--muted)]">₹{Math.round(item.listing.sellingPrice / 100)} / {item.listing.unit.toLowerCase()}</p></div><button disabled={busy} onClick={() => update(item.listingId, 0)} className="rounded-lg p-2 text-[var(--muted)] hover:bg-[var(--surface-muted)] hover:text-[var(--accent-strong)]" aria-label={`Remove ${item.listing.name}`}><Trash2 className="size-4" /></button></div><p className="mt-2 inline-flex items-center gap-1.5 text-xs font-semibold text-[var(--muted)]"><Clock3 className="size-3.5 text-[var(--accent)]" />Pickup until {new Date(item.listing.pickupEnd).toLocaleTimeString("en-IN", { hour: "numeric", minute: "2-digit" })}</p><div className="mt-3 flex items-center gap-2"><button disabled={busy} onClick={() => update(item.listingId, item.quantity - 1)} className="grid size-8 place-items-center rounded-lg border border-[var(--border)] bg-[var(--surface)]" aria-label="Decrease quantity"><Minus className="size-3.5" /></button><span className="grid min-w-8 place-items-center text-sm font-black">{item.quantity}</span><button disabled={busy} onClick={() => update(item.listingId, item.quantity + 1)} className="grid size-8 place-items-center rounded-lg border border-[var(--border)] bg-[var(--surface)]" aria-label="Increase quantity"><Plus className="size-3.5" /></button></div></div></article>)}</section><aside className="surface-card p-6 lg:sticky lg:top-24"><p className="page-kicker">Order summary</p><h2 className="mt-2 text-2xl font-black">Ready when you are</h2><div className="mt-6 flex justify-between text-sm font-semibold"><span className="text-[var(--muted)]">Subtotal</span><span>₹{Math.round(subtotal / 100)}</span></div><div className="mt-4 flex justify-between border-t border-[var(--border)] pt-4 text-lg font-black"><span>Total</span><span>₹{Math.round(subtotal / 100)}</span></div><Link href="/checkout" className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--accent)] px-4 py-3.5 text-sm font-black text-white hover:bg-[var(--accent-strong)]">Continue to checkout <ArrowRight className="size-4" /></Link><p className="mt-3 text-xs leading-5">Choose pickup or delivery at checkout where the seller supports it.</p></aside></div>;
}
