import Link from "next/link";
import { Download, Plus, Search, SlidersHorizontal } from "lucide-react";
import { requireRole } from "@/lib/authorization";
import { listOwnedListings } from "@/lib/seller-operations-domain";
import { ListingActions } from "@/components/seller/listing-actions";

export default async function SellerListingsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const user = await requireRole("SELLER"); const params = await searchParams; const query = Object.fromEntries(Object.entries(params).map(([key, value]) => [key, Array.isArray(value) ? value[0] : value]).filter(([, value]) => value)); const result = await listOwnedListings(user.id, query);
  return <main className="product-page"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="page-kicker">Seller catalog</p><h1 className="mt-3 text-4xl font-black sm:text-5xl">Surplus food listings</h1><p className="mt-3 max-w-2xl">Keep active offers fresh, visible, and easy to operate from one workspace.</p></div><div className="flex flex-wrap gap-2"><a href="/api/seller/export?kind=listings" className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-4 py-3 text-sm font-black"><Download className="size-4" />Export CSV</a><Link href="/seller/listings/new" className="inline-flex items-center gap-2 rounded-xl bg-[var(--accent)] px-4 py-3 text-sm font-black text-white"><Plus className="size-4" />Add surplus food</Link></div></div>
    <form className="surface-card mt-7 grid gap-3 p-4 sm:grid-cols-[1fr_190px_auto]"><div className="relative"><Search className="pointer-events-none absolute left-3 top-3.5 size-4 text-[var(--muted)]" /><input name="q" defaultValue={query.q ?? ""} placeholder="Search listings" className="w-full pl-10" /></div><select name="status" defaultValue={query.status ?? ""}><option value="">All statuses</option>{["DRAFT", "PENDING_REVIEW", "ACTIVE", "PAUSED", "SOLD_OUT", "EXPIRED", "CANCELLED"].map((status) => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</select><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-[var(--foreground)] px-5 py-3 text-sm font-black text-[var(--background)]"><SlidersHorizontal className="size-4" />Filter</button></form>
    {result.listings.length === 0 ? <div className="empty-state mt-6"><h2 className="text-xl font-black">No listings match</h2><p className="mt-2">Try another status or search term.</p><Link href="/seller/listings/new" className="mt-5 inline-flex rounded-xl bg-[var(--accent)] px-4 py-3 text-sm font-black text-white">Create your first listing</Link></div> : <div className="table-wrap mt-6"><table><thead><tr><th>Listing</th><th>Status</th><th>Available</th><th>Reserved</th><th>Pickup ends</th><th>Actions</th></tr></thead><tbody>{result.listings.map((listing) => <tr key={listing.id}><td><span className="font-black">{listing.name}</span><span className="block text-xs text-[var(--muted)]">{listing.category.name}</span></td><td><span className="status-chip">{listing.status.replaceAll("_", " ")}</span></td><td>{listing.inventory?.availableQuantity ?? "—"} {listing.unit.toLowerCase()}</td><td>{listing.inventory?.reservedQuantity ?? "—"}</td><td>{listing.pickupEnd.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}</td><td><ListingActions id={listing.id} status={listing.status} /></td></tr>)}</tbody></table><p className="px-4 py-3 text-xs font-semibold text-[var(--muted)]">Page {result.page} of {Math.max(result.pages, 1)} · {result.total} listing(s)</p></div>}
  </main>;
}
