import crypto from "node:crypto";
import { OrderStatus, PaymentStatus, Prisma, ReservationStatus } from "@prisma/client";
import { cartItemSchema, cartUpdateSchema, checkoutSchema, orderTransitionSchema, cancellationSchema, pickupVerificationSchema, paymentWebhookSchema } from "@foodbite/validation";
import { prisma } from "@/lib/prisma";

const reservationMinutes = Number(process.env.RESERVATION_MINUTES ?? 15);
const paymentProvider = process.env.PAYMENT_PROVIDER ?? "UNCONFIGURED";
const hash = (value: string) => crypto.createHash("sha256").update(value).digest("hex");
const pickupCode = () => String(crypto.randomInt(100000, 1000000));
const orderNumber = () => `FB-${new Date().getFullYear()}-${crypto.randomBytes(4).toString("hex").toUpperCase()}`;

export function orderTransitionAllowed(from: OrderStatus, to: OrderStatus) { const transitions: Record<OrderStatus, OrderStatus[]> = { PENDING_PAYMENT: ["PAID", "CANCELLED"], PAID: ["CONFIRMED", "CANCELLED", "REFUND_PENDING"], CONFIRMED: ["PREPARING", "CANCELLED", "REFUND_PENDING"], PREPARING: ["READY_FOR_PICKUP"], READY_FOR_PICKUP: ["PICKED_UP"], PICKED_UP: ["COMPLETED"], COMPLETED: [], CANCELLED: [], REFUND_PENDING: ["REFUNDED"], REFUNDED: [] }; return transitions[from].includes(to); }
export function inventoryTotals(total: number, available: number, reserved: number, sold: number) { if (total !== available + reserved + sold || [total, available, reserved, sold].some((v) => v < 0)) throw new Error("Inventory invariant violated"); return true; }
export function verifyWebhookSignature(rawBody: string, signature: string | null) { const secret = process.env.PAYMENT_WEBHOOK_SECRET; if (!secret || !signature) return false; const expected = crypto.createHmac("sha256", secret).update(rawBody).digest("hex"); return expected.length === signature.length && crypto.timingSafeEqual(Buffer.from(expected), Buffer.from(signature)); }

async function buyer(userId: string) { const user = await prisma.user.findFirst({ where: { id: userId, role: "BUYER", status: "ACTIVE" }, select: { id: true } }); if (!user) throw new Error("Active buyer access is required."); return user; }
async function seller(userId: string) { const profile = await prisma.sellerProfile.findFirst({ where: { userId, user: { role: "SELLER", status: "ACTIVE" } }, select: { id: true } }); if (!profile) throw new Error("Active seller access is required."); return profile; }

const cartInclude = {
  items: {
    orderBy: { createdAt: "asc" as const },
    include: {
      listing: {
        select: {
          id: true, name: true, sellingPrice: true, unit: true, pickupStart: true, pickupEnd: true, sellerId: true, status: true,
          seller: { select: { business: { select: { name: true, address: true, city: true } } } },
          inventory: { select: { availableQuantity: true } },
          images: { select: { url: true, altText: true }, orderBy: { sortOrder: "asc" as const }, take: 1 }
        }
      }
    }
  }
};

export async function getCart(userId: string) { await buyer(userId); return prisma.cart.findUnique({ where: { userId }, include: cartInclude }); }
export async function addToCart(userId: string, input: unknown) { await buyer(userId); const parsed = cartItemSchema.parse(input); const listing = await prisma.foodListing.findFirst({ where: { id: parsed.listingId, status: "ACTIVE", pickupEnd: { gt: new Date() }, inventory: { is: { availableQuantity: { gt: 0 } } }, seller: { user: { status: "ACTIVE" }, businessId: { not: null } } }, select: { id: true, sellerId: true } }); if (!listing) throw new Error("This listing is no longer available."); const cart = await prisma.cart.upsert({ where: { userId }, create: { userId }, update: {} }); const existing = await prisma.cartItem.findFirst({ where: { cartId: cart.id }, include: { listing: { select: { sellerId: true } } } }); if (existing && existing.listing.sellerId !== listing.sellerId) throw new Error("Your cart contains items from another seller. FoodBite currently supports one seller per order."); await prisma.cartItem.upsert({ where: { cartId_listingId: { cartId: cart.id, listingId: parsed.listingId } }, create: { cartId: cart.id, listingId: parsed.listingId, quantity: parsed.quantity }, update: { quantity: { increment: parsed.quantity } } }); return getCart(userId); }
export async function updateCartItem(userId: string, listingId: string, input: unknown) { await buyer(userId); const parsed = cartUpdateSchema.parse(input); const cart = await prisma.cart.findUnique({ where: { userId } }); if (!cart) throw new Error("Cart not found."); await prisma.cartItem.updateMany({ where: { cartId: cart.id, listingId }, data: { quantity: parsed.quantity } }); return getCart(userId); }
export async function removeCartItem(userId: string, listingId: string) { await buyer(userId); const cart = await prisma.cart.findUnique({ where: { userId } }); if (cart) await prisma.cartItem.deleteMany({ where: { cartId: cart.id, listingId } }); return getCart(userId); }

export async function createCheckout(userId: string, input: unknown) { await buyer(userId); const parsed = checkoutSchema.parse(input); const existing = await prisma.order.findUnique({ where: { buyerId_idempotencyKey: { buyerId: userId, idempotencyKey: parsed.idempotencyKey } }, include: { payments: true, pickup: true } }); if (existing) return { order: existing, paymentConfigured: paymentProvider !== "UNCONFIGURED" };
  const cart = await prisma.cart.findUnique({ where: { userId }, include: cartInclude }); if (!cart || cart.items.length === 0) throw new Error("Your cart is empty."); const now = new Date(); const sellerId = cart.items[0].listing.sellerId; if (cart.items.some((item) => item.listing.sellerId !== sellerId)) throw new Error("Your cart contains items from another seller. FoodBite currently supports one seller per order."); const total = cart.items.reduce((sum, item) => sum + item.listing.sellingPrice * item.quantity, 0);
  const result = await prisma.$transaction(async (tx) => { const order = await tx.order.create({ data: { orderNumber: orderNumber(), buyerId: userId, sellerId, idempotencyKey: parsed.idempotencyKey, subtotal: total, totalAmount: total, discount: 0, status: "PENDING_PAYMENT", items: { create: cart.items.map((item) => ({ listingId: item.listing.id, listingNameSnapshot: item.listing.name, unitPrice: item.listing.sellingPrice, quantity: item.quantity, totalPrice: item.listing.sellingPrice * item.quantity, foodTypeSnapshot: "OTHER", pickupStartSnapshot: item.listing.pickupStart, pickupEndSnapshot: item.listing.pickupEnd })) } } }); for (const item of cart.items) { if (item.listing.status !== "ACTIVE" || item.listing.pickupEnd <= now || !item.listing.inventory || item.listing.inventory.availableQuantity < item.quantity) throw new Error(`Only ${item.listing.inventory?.availableQuantity ?? 0} ${item.listing.unit.toLowerCase()} are currently available.`); const reserved = await tx.inventory.updateMany({ where: { listingId: item.listing.id, availableQuantity: { gte: item.quantity } }, data: { availableQuantity: { decrement: item.quantity }, reservedQuantity: { increment: item.quantity }, version: { increment: 1 } } }); if (reserved.count !== 1) throw new Error("Inventory changed. Please review your cart and try again."); await tx.reservation.create({ data: { orderId: order.id, listingId: item.listing.id, quantity: item.quantity, expiresAt: new Date(Date.now() + reservationMinutes * 60_000) } }); } const payment = await tx.payment.create({ data: { orderId: order.id, provider: paymentProvider, amount: total, status: "CREATED" } }); await tx.cartItem.deleteMany({ where: { cartId: cart.id } }); return { order: await tx.order.findUniqueOrThrow({ where: { id: order.id }, include: { items: true, reservations: true, payments: true } }), payment }; }); return { ...result, paymentConfigured: paymentProvider !== "UNCONFIGURED" }; }

export async function transitionSellerOrder(userId: string, orderId: string, input: unknown) { const sellerProfile = await seller(userId); const parsed = orderTransitionSchema.parse(input); const order = await prisma.order.findFirst({ where: { id: orderId, sellerId: sellerProfile.id }, select: { id: true, status: true } }); if (!order || !orderTransitionAllowed(order.status, parsed.status)) throw new Error("Order transition is not allowed."); return prisma.order.update({ where: { id: order.id }, data: { status: parsed.status } }); }

export async function handlePaymentWebhook(rawBody: string, signature: string | null) { if (!verifyWebhookSignature(rawBody, signature)) throw new Error("Invalid payment signature."); const parsed = paymentWebhookSchema.parse(JSON.parse(rawBody)); return prisma.$transaction(async (tx) => { const webhook = await tx.paymentWebhook.create({ data: { provider: parsed.provider, eventId: parsed.eventId, eventType: parsed.eventType, payloadHash: hash(rawBody), processedAt: new Date() } }).catch((error: unknown) => { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") return null; throw error; }); if (!webhook) return { duplicate: true }; const payment = await tx.payment.findFirst({ where: { orderId: parsed.orderId, provider: parsed.provider }, select: { id: true, orderId: true, status: true } }); if (!payment) throw new Error("Payment not found."); if (parsed.status === "SUCCESS") { await tx.payment.update({ where: { id: payment.id }, data: { status: "SUCCESS", providerPaymentId: parsed.providerPaymentId } }); await tx.order.update({ where: { id: payment.orderId }, data: { status: "CONFIRMED" } }); const reservations = await tx.reservation.findMany({ where: { orderId: payment.orderId, status: "ACTIVE" } }); for (const reservation of reservations) { await tx.reservation.update({ where: { id: reservation.id }, data: { status: "CONFIRMED" } }); await tx.inventory.update({ where: { listingId: reservation.listingId }, data: { reservedQuantity: { decrement: reservation.quantity }, soldQuantity: { increment: reservation.quantity }, version: { increment: 1 } } }); } const code = pickupCode(); await tx.pickup.upsert({ where: { orderId: payment.orderId }, create: { orderId: payment.orderId, pickupCodeHash: hash(code) }, update: {} }); } else { await tx.payment.update({ where: { id: payment.id }, data: { status: parsed.status === "FAILED" ? "FAILED" : "REFUNDED" } }); await tx.order.update({ where: { id: payment.orderId }, data: { status: "CANCELLED", cancelledAt: new Date() } }); const reservations = await tx.reservation.findMany({ where: { orderId: payment.orderId, status: "ACTIVE" } }); for (const reservation of reservations) { await tx.reservation.update({ where: { id: reservation.id }, data: { status: "CANCELLED" } }); await tx.inventory.update({ where: { listingId: reservation.listingId }, data: { reservedQuantity: { decrement: reservation.quantity }, availableQuantity: { increment: reservation.quantity }, version: { increment: 1 } } }); } } return { duplicate: false }; }); }

export async function expireReservations() { const expired = await prisma.reservation.findMany({ where: { status: "ACTIVE", expiresAt: { lte: new Date() } }, select: { id: true, orderId: true, listingId: true, quantity: true } }); let released = 0; for (const reservation of expired) { await prisma.$transaction(async (tx) => { const claimed = await tx.reservation.updateMany({ where: { id: reservation.id, status: "ACTIVE" }, data: { status: "EXPIRED" } }); if (!claimed.count) return; await tx.inventory.update({ where: { listingId: reservation.listingId }, data: { reservedQuantity: { decrement: reservation.quantity }, availableQuantity: { increment: reservation.quantity }, version: { increment: 1 } } }); await tx.order.update({ where: { id: reservation.orderId }, data: { status: "CANCELLED", cancelledAt: new Date() } }); released += 1; }); } return { released }; }

export async function cancelOrder(userId: string, orderId: string, input: unknown) { await buyer(userId); cancellationSchema.parse(input); return prisma.$transaction(async (tx) => { const order = await tx.order.findFirst({ where: { id: orderId, buyerId: userId }, include: { reservations: true, payments: true } }); if (!order) throw new Error("Order not found."); if (order.status === "PENDING_PAYMENT") { for (const reservation of order.reservations.filter((r) => r.status === "ACTIVE")) { await tx.reservation.update({ where: { id: reservation.id }, data: { status: "CANCELLED" } }); await tx.inventory.update({ where: { listingId: reservation.listingId }, data: { reservedQuantity: { decrement: reservation.quantity }, availableQuantity: { increment: reservation.quantity }, version: { increment: 1 } } }); } return tx.order.update({ where: { id: order.id }, data: { status: "CANCELLED", cancelledAt: new Date() } }); } if (["PAID", "CONFIRMED"].includes(order.status)) return tx.order.update({ where: { id: order.id }, data: { status: "REFUND_PENDING", cancelledAt: new Date() } }); throw new Error("This order cannot be cancelled."); }); }

export async function verifyPickup(userId: string, orderId: string, input: unknown) { const sellerProfile = await seller(userId); const parsed = pickupVerificationSchema.parse(input); return prisma.$transaction(async (tx) => { const order = await tx.order.findFirst({ where: { id: orderId, sellerId: sellerProfile.id }, include: { pickup: true } }); if (!order || !order.pickup) throw new Error("Pickup not found."); if (order.status === "COMPLETED") return order; if (order.status === "PICKED_UP") return tx.order.update({ where: { id: orderId }, data: { status: "COMPLETED", completedAt: new Date() } }); if (order.status !== "READY_FOR_PICKUP") throw new Error("Order is not ready for pickup."); if (hash(parsed.pickupCode) !== order.pickup.pickupCodeHash) throw new Error("Pickup code is invalid."); await tx.pickup.update({ where: { orderId }, data: { verifiedAt: new Date(), verifiedBy: userId } }); return tx.order.update({ where: { id: orderId }, data: { status: "PICKED_UP" } }); }); }

export { hash, pickupCode, reservationMinutes };

const orderInclude = { items: true, payments: { orderBy: { createdAt: "desc" as const }, take: 1 }, reservations: true, pickup: true, seller: { select: { business: { select: { name: true, address: true, city: true, state: true } } } } };
export async function getBuyerOrders(userId: string) { await buyer(userId); return prisma.order.findMany({ where: { buyerId: userId }, include: orderInclude, orderBy: { createdAt: "desc" } }); }
export async function getBuyerOrder(userId: string, orderId: string) { await buyer(userId); return prisma.order.findFirst({ where: { id: orderId, buyerId: userId }, include: orderInclude }); }
export async function getSellerOrders(userId: string) { const profile = await seller(userId); return prisma.order.findMany({ where: { sellerId: profile.id }, include: { items: true, payments: { orderBy: { createdAt: "desc" as const }, take: 1 }, pickup: true, buyer: { select: { id: true, email: true, phone: true, buyerProfile: { select: { name: true } } } } }, orderBy: { createdAt: "desc" } }); }
export async function getSellerOrder(userId: string, orderId: string) { const profile = await seller(userId); return prisma.order.findFirst({ where: { id: orderId, sellerId: profile.id }, include: { items: true, payments: { orderBy: { createdAt: "desc" as const }, take: 1 }, pickup: true, buyer: { select: { id: true, email: true, phone: true, buyerProfile: { select: { name: true } } } } } }); }
