import { prisma } from "@/lib/prisma";
import { marketplaceQuerySchema, type MarketplaceQuery } from "@foodbite/validation";

const pageSize = 24;
export function haversineKm(lat1: number, lng1: number, lat2: number, lng2: number) { const earth = 6371; const dLat = (lat2 - lat1) * Math.PI / 180; const dLng = (lng2 - lng1) * Math.PI / 180; const a = Math.sin(dLat / 2) ** 2 + Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * Math.sin(dLng / 2) ** 2; return earth * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)); }
export function discountPercent(originalPrice: number, sellingPrice: number) { return originalPrice > 0 ? Math.max(0, Math.min(100, Math.round(((originalPrice - sellingPrice) / originalPrice) * 100))) : 0; }
export function parseMarketplaceQuery(searchParams: URLSearchParams | Record<string, string | string[] | undefined>): MarketplaceQuery { const entries = searchParams instanceof URLSearchParams ? Object.fromEntries(searchParams.entries()) : Object.fromEntries(Object.entries(searchParams).map(([key, value]) => [key, Array.isArray(value) ? value[0] : value])); const result = marketplaceQuerySchema.safeParse(entries); return result.success ? result.data : marketplaceQuerySchema.parse({}); }

const select = { id: true, slug: true, name: true, description: true, listingType: true, foodType: true, originalPrice: true, sellingPrice: true, quantity: true, unit: true, preparedAt: true, pickupStart: true, pickupEnd: true, packagingInfo: true, allergenInfo: true, status: true, images: { select: { url: true, altText: true, sortOrder: true }, orderBy: { sortOrder: "asc" as const }, take: 1 }, category: { select: { name: true, slug: true } }, inventory: { select: { availableQuantity: true } }, seller: { select: { business: { select: { name: true, type: true, city: true, state: true, latitude: true, longitude: true, verificationStatus: true } } } } };

export async function getMarketplaceListings(raw: URLSearchParams | Record<string, string | string[] | undefined>) { const query = parseMarketplaceQuery(raw); const now = new Date(); const where = { status: "ACTIVE" as const, pickupEnd: { gt: now }, inventory: { is: { availableQuantity: { gt: 0 } } }, seller: { user: { status: "ACTIVE" as const }, businessId: { not: null } }, ...(query.foodType ? { foodType: query.foodType } : {}), ...(query.category ? { category: { slug: query.category } } : {}), ...(query.city ? { seller: { business: { city: { equals: query.city, mode: "insensitive" as const } }, user: { status: "ACTIVE" as const }, businessId: { not: null } } } : {}), ...(query.minPrice !== undefined || query.maxPrice !== undefined ? { sellingPrice: { ...(query.minPrice !== undefined ? { gte: query.minPrice * 100 } : {}), ...(query.maxPrice !== undefined ? { lte: query.maxPrice * 100 } : {}) } } : {}), ...(query.q ? { OR: [{ name: { contains: query.q, mode: "insensitive" as const } }, { description: { contains: query.q, mode: "insensitive" as const } }, { category: { name: { contains: query.q, mode: "insensitive" as const } } }, { seller: { business: { name: { contains: query.q, mode: "insensitive" as const } } } }] } : {}) };
  const orderBy = query.sort === "ending-soon" ? { pickupEnd: "asc" as const } : query.sort === "lowest-price" ? { sellingPrice: "asc" as const } : { createdAt: "desc" as const };
  const [listings, total] = await prisma.$transaction([prisma.foodListing.findMany({ where, select, orderBy, skip: (query.page - 1) * pageSize, take: pageSize }), prisma.foodListing.count({ where })]);
  const withDistance = listings.map((listing) => { const business = listing.seller.business; const distanceKm = query.lat !== undefined && query.lng !== undefined && business?.latitude != null && business.longitude != null ? haversineKm(query.lat, query.lng, Number(business.latitude), Number(business.longitude)) : null; return { ...listing, discountPercent: discountPercent(listing.originalPrice, listing.sellingPrice), distanceKm }; });
  if (query.sort === "nearest") withDistance.sort((a, b) => (a.distanceKm ?? Number.POSITIVE_INFINITY) - (b.distanceKm ?? Number.POSITIVE_INFINITY));
  if (query.sort === "highest-discount") withDistance.sort((a, b) => b.discountPercent - a.discountPercent);
  return { listings: withDistance, total, page: query.page, pageSize, totalPages: Math.max(1, Math.ceil(total / pageSize)), query };
}

export async function getMarketplaceListing(slug: string) { const listing = await prisma.foodListing.findFirst({ where: { slug, status: "ACTIVE", pickupEnd: { gt: new Date() }, inventory: { is: { availableQuantity: { gt: 0 } } }, seller: { user: { status: "ACTIVE" }, businessId: { not: null } } }, select }); return listing ? { ...listing, discountPercent: discountPercent(listing.originalPrice, listing.sellingPrice) } : null; }
export async function getMarketplaceCategories() { return prisma.foodCategory.findMany({ where: { isActive: true }, select: { name: true, slug: true, imageUrl: true }, orderBy: { sortOrder: "asc" } }); }
export async function getMarketplaceListingsSafe(raw: URLSearchParams | Record<string, string | string[] | undefined>) { const query = parseMarketplaceQuery(raw); try { return { ...(await getMarketplaceListings(raw)), databaseError: false }; } catch { return { listings: [], total: 0, page: query.page, pageSize, totalPages: 1, query, databaseError: true }; } }
export async function getMarketplaceCategoriesSafe() { try { return await getMarketplaceCategories(); } catch { return []; } }
export async function getMarketplaceListingSafe(slug: string) { try { return await getMarketplaceListing(slug); } catch { return null; } }
