import Link from "next/link";
import { ArrowRight, BarChart3, Boxes, ClipboardList, HeartHandshake, Plus } from "lucide-react";
import { requireRole } from "@/lib/authorization";
import { getSellerOperationalSummary } from "@/lib/seller-operations-domain";
import { SellerInsightsPanel } from "@/components/seller/ai-panels";

export default async function SellerDashboardPage() {
  const user = await requireRole("SELLER"); const summary = await getSellerOperationalSummary(user.id);
  const cards = [["Active listings", summary.listings.active, "Live now"], ["Paused listings", summary.listings.paused, "Needs attention"], ["Expiring in 24h", summary.listings.expiringSoon, "Act soon"], ["Available surplus", summary.inventory.availableQuantity ?? 0, "Units available"], ["Low-stock listings", summary.listings.lowStock, "Watch inventory"]];
  return <main className="product-page"><section className="hero-panel px-6 py-8 sm:px-9 sm:py-10"><div className="relative z-10 flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="page-kicker">Seller workspace</p><h1 className="mt-3">Good morning. Move surplus with confidence.</h1><p className="mt-4 max-w-2xl leading-7">A focused view of your live listings, inventory, orders, and donation recovery.</p></div><div className="flex flex-wrap gap-2"><Link href="/seller/listings/new" className="inline-flex items-center gap-2 rounded-xl bg-[var(--accent)] px-4 py-3 text-sm font-black text-white"><Plus className="size-4" />Add surplus food</Link><Link href="/seller/business" className="inline-flex items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-4 py-3 text-sm font-black">Business settings</Link></div></div></section>
    <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{cards.map(([label, value, hint]) => <div key={String(label)} className="metric-card"><p className="metric-label">{label}</p><p className="metric-value">{value}</p><p className="mt-2 text-xs font-semibold">{hint}</p></div>)}</section>
    <div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="surface-card p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[var(--surface-muted)]"><ClipboardList className="size-5 text-[var(--accent)]" /></span><h2 className="text-xl font-black">Order operations</h2></div><Link href="/seller/orders" className="text-sm font-bold">View all</Link></div><div className="mt-5 grid grid-cols-2 gap-3">{Object.entries(summary.orders).map(([status, count]) => <div key={status} className="rounded-2xl bg-[var(--surface-muted)] p-4"><p className="text-xs font-bold uppercase tracking-wide">{status.replaceAll("_", " ")}</p><p className="mt-2 text-2xl font-black">{count}</p></div>)}</div></section><section className="surface-card p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[var(--accent-soft)]"><HeartHandshake className="size-5 text-[var(--accent)]" /></span><h2 className="text-xl font-black">Donation recovery</h2></div><Link href="/seller/donations" className="text-sm font-bold">View all</Link></div><div className="mt-5 grid grid-cols-2 gap-3">{Object.entries(summary.donations).map(([status, count]) => <div key={status} className="rounded-2xl bg-[var(--accent-soft)] p-4"><p className="text-xs font-bold uppercase tracking-wide">{status.replaceAll("_", " ")}</p><p className="mt-2 text-2xl font-black">{count}</p></div>)}</div></section></div>
    <section className="surface-card mt-5 p-6"><div className="flex items-center gap-3"><Boxes className="size-5 text-[var(--accent)]" /><h2 className="text-xl font-black">Inventory accounting</h2></div><div className="mt-5 grid gap-3 sm:grid-cols-4">{[["Available", summary.inventory.availableQuantity ?? 0],["Reserved", summary.inventory.reservedQuantity ?? 0],["Sold", summary.inventory.soldQuantity ?? 0],["Donated", summary.inventory.donatedQuantity ?? 0]].map(([label,value]) => <div key={String(label)} className="surface-muted p-4"><p className="text-xs font-bold uppercase tracking-wide">{label}</p><p className="mt-2 text-xl font-black">{value}</p></div>)}</div><p className="mt-5 text-xs">Food information is provided by sellers. FoodBite does not certify food safety.</p></section>
    <div className="mt-5"><SellerInsightsPanel /></div><div className="mt-5 flex flex-wrap gap-2 text-xs font-bold"><Link href="/seller/listings" className="inline-flex items-center gap-1 rounded-full border border-[var(--border)] bg-[var(--surface)] px-3 py-2">Manage listings <ArrowRight className="size-3" /></Link><Link href="/seller/analytics" className="inline-flex items-center gap-1 rounded-full border border-[var(--border)] bg-[var(--surface)] px-3 py-2"><BarChart3 className="size-3" />Open analytics</Link></div>
  </main>;
}
