import Link from "next/link";
import { requireRole } from "@/lib/authorization";
import { prisma } from "@/lib/prisma";

export default async function SellerDashboardPage() {
  const user = await requireRole("SELLER");
  const seller = await prisma.sellerProfile.findUnique({ where: { userId: user.id }, include: { business: true } });
  const listings = seller ? await prisma.foodListing.findMany({ where: { sellerId: seller.id }, include: { inventory: true }, orderBy: { createdAt: "desc" }, take: 100 }) : [];
  const counts = { active: listings.filter((l) => l.status === "ACTIVE").length, drafts: listings.filter((l) => l.status === "DRAFT").length, endingSoon: listings.filter((l) => l.status === "ACTIVE" && l.pickupEnd.getTime() - Date.now() < 24 * 60 * 60 * 1000).length, listed: listings.reduce((sum, l) => sum + (l.inventory?.totalQuantity ?? 0), 0), sold: listings.reduce((sum, l) => sum + (l.inventory?.soldQuantity ?? 0), 0) };
  return <main className="mx-auto max-w-6xl px-6 py-12"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-[#e85d3f]">Seller workspace</p><h1 className="mt-3 text-4xl font-bold text-[#173f3b]">Turn surplus into value.</h1><p className="mt-3 text-[#55706c]">{seller?.business?.name ?? "Set up your business to start listing surplus food."}</p></div><Link href="/seller/listings/new" className="rounded-lg bg-[#e85d3f] px-5 py-3 text-center font-semibold text-white hover:bg-[#cf4d32]">Add surplus food</Link></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[["Active listings", counts.active], ["Drafts", counts.drafts], ["Ending soon", counts.endingSoon], ["Listed quantity", counts.listed], ["Sold quantity", counts.sold]].map(([label, value]) => <div key={String(label)} className="rounded-xl border border-[#dbe4df] bg-white p-5"><p className="text-sm text-[#55706c]">{label}</p><p className="mt-3 text-3xl font-bold text-[#173f3b]">{value}</p></div>)}</div><section className="mt-10 rounded-2xl border border-[#dbe4df] bg-white p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-bold text-[#173f3b]">Business verification</h2><span className="rounded-full bg-[#fff1e9] px-3 py-1 text-sm font-semibold text-[#b33f2d]">{seller?.verificationStatus ?? "PENDING"}</span></div><p className="mt-3 text-sm leading-6 text-[#55706c]">Verification status reflects the current seller record. Providing business information does not mean the business is verified.</p><Link href="/seller/business" className="mt-4 inline-block font-semibold text-[#173f3b] underline">Maintain business information</Link></section></main>;
}
