import Link from "next/link";
import { redirect, notFound } from "next/navigation";
import { PickupCode } from "@/components/checkout/pickup-code";
import { getCurrentUser } from "@/lib/auth";
import { getBuyerOrder } from "@/lib/order-domain";

export default async function OrderDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await getCurrentUser(); if (!user || user.role !== "BUYER") redirect("/login");
  const { id } = await params; const order = await getBuyerOrder(user.id, id); if (!order) notFound();
  return <main className="mx-auto max-w-5xl px-6 py-12 lg:px-10"><Link href="/orders" className="text-sm font-semibold text-[#55706c] underline">← Orders</Link><div className="mt-6 flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm uppercase tracking-[.18em] text-[#e85d3f]">Order</p><h1 className="mt-2 text-4xl font-bold text-[#173f3b]">{order.orderNumber}</h1><p className="mt-2 text-[#55706c]">{new Date(order.createdAt).toLocaleString("en-IN")}</p></div><span className="rounded-full bg-[#eef2ef] px-4 py-2 font-bold text-[#173f3b]">{order.status.replaceAll("_", " ")}</span></div><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_320px]"><section className="space-y-4">{order.items.map((item) => <article key={item.id} className="rounded-2xl border border-[#dbe4df] p-5"><div className="flex justify-between gap-4"><div><h2 className="font-bold text-[#173f3b]">{item.listingName}</h2><p className="mt-1 text-sm text-[#55706c]">{item.quantity} × ₹{Math.round(item.unitPrice / 100)}</p></div><p className="font-bold text-[#173f3b]">₹{Math.round(item.lineTotal / 100)}</p></div></article>)}<div className="rounded-2xl border border-[#dbe4df] p-5"><h2 className="font-bold text-[#173f3b]">Pickup</h2><p className="mt-2 text-sm text-[#55706c]">{order.items[0]?.seller?.business?.name ?? "Seller location"}</p><p className="mt-1 text-sm text-[#55706c]">{order.items[0]?.seller?.business?.address ?? "Address is provided by the seller."}</p><PickupCode orderId={order.id} /><p className="mt-4 text-xs text-[#8a9b96]">If you no longer have the code, contact support before pickup.</p></div></section><aside className="h-fit rounded-3xl border border-[#dbe4df] p-6"><h2 className="text-xl font-bold text-[#173f3b]">Payment</h2><p className="mt-5 flex justify-between text-[#55706c]"><span>Subtotal</span><span>₹{Math.round(order.subtotal / 100)}</span></p><p className="mt-4 flex justify-between border-t pt-4 text-lg font-bold text-[#173f3b]"><span>Total</span><span>₹{Math.round(order.totalAmount / 100)}</span></p><p className="mt-4 text-sm text-[#55706c]">{order.payment?.status.replaceAll("_", " ") ?? "Pending"}</p></aside></div></main>;
}
