import Link from "next/link";
import { Clock3, MapPin, PackageCheck } from "lucide-react";
import { FavoriteButton } from "./favorite-button";

export type CardListing = { id: string; slug: string; name: string; listingType: string; foodType: string; originalPrice: number; sellingPrice: number; pickupEnd: Date; quantity: number; unit: string; inventory: { availableQuantity: number } | null; category: { name: string; slug: string }; images: { url: string; altText: string }[]; seller: { business: { name: string; city: string | null; verificationStatus: string } | null }; discountPercent: number; distanceKm: number | null };

export function FoodCard({ listing }: { listing: CardListing }) {
  const image = listing.images[0];
  return <article className="group overflow-hidden rounded-[22px] border border-[var(--border)] bg-[var(--surface)] shadow-[0_10px_30px_color-mix(in_srgb,var(--foreground)_5%,transparent)] transition duration-200 hover:-translate-y-1 hover:shadow-[0_18px_42px_color-mix(in_srgb,var(--foreground)_10%,transparent)]">
    <div className="relative aspect-[4/3] overflow-hidden bg-[var(--surface-muted)]">{image ? <img src={image.url} alt={image.altText} className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]" /> : <div className="grid h-full place-items-center text-sm font-bold text-[var(--muted)]">Surplus food</div>}<div className="absolute inset-x-0 top-0 flex items-center justify-between p-3"><span className="rounded-full bg-[var(--surface)]/95 px-3 py-1.5 text-xs font-black text-[var(--foreground)]">{listing.discountPercent}% off</span><FavoriteButton listingId={listing.id} /></div></div>
    <div className="p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-[11px] font-black uppercase tracking-[.14em] text-[var(--accent)]">{listing.category.name}</p><h2 className="mt-2 truncate text-lg font-black tracking-tight text-[var(--foreground)]">{listing.name}</h2><p className="mt-1 truncate text-sm text-[var(--muted)]">{listing.seller.business?.name ?? "Local food business"}</p></div><span className="shrink-0 rounded-full bg-[var(--surface-muted)] px-2.5 py-1 text-[10px] font-extrabold text-[var(--foreground)]">{listing.foodType.replaceAll("_", " ")}</span></div>
      <div className="mt-5 flex items-end justify-between gap-3"><div><span className="text-2xl font-black text-[var(--foreground)]">₹{Math.round(listing.sellingPrice / 100)}</span><span className="ml-2 text-sm text-[var(--muted)] line-through">₹{Math.round(listing.originalPrice / 100)}</span></div><span className="text-xs font-bold text-[var(--muted)]">{listing.inventory?.availableQuantity ?? 0} {listing.unit.toLowerCase()} left</span></div>
      <div className="mt-4 grid gap-2 text-xs font-semibold text-[var(--muted)]"><span className="inline-flex items-center gap-2"><Clock3 className="size-3.5 text-[var(--accent)]" />Pickup until {listing.pickupEnd.toLocaleTimeString("en-IN", { hour: "numeric", minute: "2-digit" })}</span><span className="inline-flex items-center gap-2"><MapPin className="size-3.5 text-[var(--accent)]" />{listing.distanceKm === null ? listing.seller.business?.city ?? "Pickup" : `${listing.distanceKm.toFixed(1)} km away`}</span></div>
      <Link href={`/food/${listing.slug}`} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--foreground)] px-4 py-3 text-sm font-extrabold text-[var(--background)] transition hover:opacity-90"><PackageCheck className="size-4" />View food details</Link>
    </div>
  </article>;
}
