/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, BarChart3, CalendarDays } from "lucide-react";

export function AnalyticsView({ title, subtitle, data, admin = false }: { title: string; subtitle: string; data: any; admin?: boolean }) {
  const range = data.range;
  const cards = admin ? [["Completed orders", data.orders.byStatus.COMPLETED ?? 0], ["Completed order value", `₹${Math.round((data.orders.completedOrderValuePaise ?? 0) / 100)}`], ["Successful payments", data.payments.byStatus.SUCCESS ?? 0], ["Donated quantity", data.recovery.donatedQuantity ?? 0], ["Delivery completed", data.fulfillment.deliveryByStatus.DELIVERED ?? 0]] : [["Total orders", data.orders.total], ["Completed orders", data.orders.completed], ["Completed order value", `₹${Math.round((data.sales.successfulOrderValuePaise ?? 0) / 100)}`], ["Sold quantity", data.inventory.soldQuantity ?? 0], ["Donated quantity", data.surplusRecovery.donatedQuantity ?? 0], ["Donation completion", data.surplusRecovery.completionRatePercent === null ? "N/A" : `${data.surplusRecovery.completionRatePercent}%`]];
  return <main className="product-page"><section className="hero-panel px-6 py-8 sm:px-9 sm:py-10"><div className="relative z-10 flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p className="page-kicker">{admin ? "Platform intelligence" : "Seller intelligence"}</p><h1 className="mt-3">{title}</h1><p className="mt-4 max-w-3xl leading-7">{subtitle}</p></div><div className="flex flex-wrap gap-2">{["today", "7d", "30d", "month"].map((value) => <Link key={value} href={`?range=${value}`} className={`rounded-xl border px-3 py-2 text-xs font-extrabold transition ${range.range === value ? "border-[var(--foreground)] bg-[var(--foreground)] text-[var(--background)]" : "border-[var(--border)] bg-[var(--surface)] hover:border-[var(--foreground)]"}`}>{value === "7d" ? "7 days" : value === "30d" ? "30 days" : value === "month" ? "This month" : "Today"}</Link>)}</div></div><div className="relative z-10 mt-6 inline-flex items-center gap-2 rounded-xl bg-[var(--surface)] px-3 py-2 text-xs font-semibold text-[var(--muted)]"><CalendarDays className="size-3.5 text-[var(--accent)]" />Reporting window: {new Date(range.start).toLocaleString("en-IN", { dateStyle: "medium", timeZone: "UTC" })} – {new Date(range.end).toLocaleString("en-IN", { dateStyle: "medium", timeZone: "UTC" })} UTC</div></section>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{cards.map(([label, value]) => <div key={String(label)} className="metric-card"><p className="metric-label">{label}</p><p className="metric-value">{value}</p><div className="mt-3 inline-flex items-center gap-1 text-[10px] font-bold text-[var(--muted)]"><ArrowUpRight className="size-3 text-[var(--accent)]" />Persisted records</div></div>)}</div>
    <div className="mt-6 grid gap-5 lg:grid-cols-2">{admin ? <><MetricTable title="Order status distribution" rows={data.orders.byStatus} /><MetricTable title="Payment status distribution" rows={data.payments.byStatus} /><MetricTable title="Donation status distribution" rows={data.recovery.donationsByStatus} /><MetricTable title="Delivery status distribution" rows={data.fulfillment.deliveryByStatus} /><MetricTable title="Listing status distribution" rows={data.marketplace.listingsByStatus} /><MetricTable title="Users by role" rows={data.marketplace.usersByRole} /></> : <><MetricTable title="Order status distribution" rows={data.orders.byStatus} /><MetricTable title="Listing status distribution" rows={data.inventory.listingStatuses} /><MetricTable title="Donation status distribution" rows={data.surplusRecovery.byStatus} /><MetricTable title="Fulfillment status distribution" rows={Object.fromEntries(data.fulfillment.byMethodAndStatus.map((row: any) => [`${row.method} · ${row.status}`, row.count]))} /></>}</div>
    <div className="mt-6 flex items-start gap-3 rounded-2xl border border-[var(--border)] bg-[var(--surface-muted)] p-4 text-sm"><BarChart3 className="mt-0.5 size-4 shrink-0 text-[var(--accent)]" /><p>Metrics are descriptive and derived from persisted FoodBite records. Unsold inventory is not labeled as waste, and no predictive or fabricated metrics are shown.</p><ArrowDownRight className="mt-0.5 ml-auto size-4 shrink-0 text-[var(--muted)]" /></div>
  </main>;
}
function MetricTable({ title, rows }: { title: string; rows: Record<string, number> }) { const entries = Object.entries(rows); return <section className="surface-card p-6"><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-black">{title}</h2><span className="status-chip">{entries.length} states</span></div>{entries.length ? <table className="mt-5 w-full text-left text-sm"><caption className="sr-only">{title}</caption><thead><tr className="border-b border-[var(--border)] text-[var(--muted)]"><th className="py-2 font-bold">Status</th><th className="py-2 text-right font-bold">Count</th></tr></thead><tbody>{entries.map(([key, value]) => <tr key={key} className="border-b border-[var(--border)] last:border-0"><th className="py-3 font-bold">{key.replaceAll("_", " ")}</th><td className="py-3 text-right font-black">{value}</td></tr>)}</tbody></table> : <p className="mt-5 text-sm">No data available for this period.</p>}</section>; }
